[entryPoints]
    [entryPoints.http]
        address = ":80"
    [entryPoints.traefik]
        address = ":8080"

[api]
    insecure = true
    dashboard = true
    debug = true

[log]
    level="DEBUG"

[providers]
    [providers.docker]
        endpoint = "unix:///var/run/docker.sock"
        watch = true
        exposedByDefault = true
        swarmMode = false
